---

name: Build
run-name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

concurrency:
  group: build-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4

      - run: dotnet restore StopWatch.sln
      - run: nuget restore StopWatch.sln
      - run: dotnet build --configuration Release --no-restore StopWatch.sln
      - run: dotnet test --configuration Release --no-restore --no-build -v=detailed StopWatch.sln
